### ISSUE TITLE
Plugin not working on 2020.2 based version

### ISSUE THREAD

**Issue by BigTows** [zielu/SVNToolBox#33] opened 2020-07-31 06:44 UTC
Hello,
idea (PHPStorm), does not run together SVNToolBox plugin.

Tested on 
PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020

**Comment by zielu** [comment] 2020-07-31 19:42
Duplicate of #32

**Closed by zielu** 2020-07-31 19:42 UTC
Labels: bug
